# Generated by Django 3.2.7 on 2021-09-25 16:39

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Drink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='name')),
                ('complicated', models.CharField(choices=[('EASY', 'easy'), ('MEDIUM', 'medium'), ('HARD', 'hard')], max_length=255, verbose_name='complicated')),
                ('is_possible_to_make', models.BooleanField(default=False, verbose_name='is possible to make')),
                ('date_creation', models.DateField(auto_now_add=True, verbose_name='Date created')),
                ('date_modified', models.DateField(auto_now=True, verbose_name='Date modified')),
            ],
            options={
                'verbose_name': 'drink',
                'verbose_name_plural': 'drinks',
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('type', models.CharField(choices=[('LIQUID', 'liquid'), ('OTHER', 'other')], max_length=255, verbose_name='type')),
                ('unit', models.CharField(choices=[('LITER', 'l'), ('MILLILITER', 'ml'), ('PIECE', 'pc')], max_length=255, verbose_name='unit')),
            ],
            options={
                'verbose_name': 'ingredient',
                'verbose_name_plural': 'ingredients',
            },
        ),
        migrations.CreateModel(
            name='IngredientStorage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storage_amount', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='amount in storage')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredient_storage', to='core.ingredient', verbose_name='ingredient')),
            ],
            options={
                'verbose_name': 'ingredient in storage',
                'verbose_name_plural': 'ingredients in storage',
            },
        ),
        migrations.CreateModel(
            name='IngredientNeeded',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='amount needed')),
                ('is_enough_to_make_drink', models.BooleanField(default=False)),
                ('drink', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredient_needed', to='core.drink', verbose_name='drink')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredient_needed', to='core.ingredient', verbose_name='ingredient')),
                ('storage_ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredient_needed', to='core.ingredientstorage', verbose_name='ingredient in storage')),
            ],
            options={
                'verbose_name': 'ingredient needed',
                'verbose_name_plural': 'ingredients needed',
            },
        ),
        migrations.CreateModel(
            name='DrinkQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('CREATED', 'created'), ('ACCEPTED', 'accepted'), ('IN_PROGRESS', 'in progress'), ('COMPLETED', 'completed'), ('REJECTED', 'rejected')], max_length=255, verbose_name='complicated')),
                ('drink', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drink_queue', to='core.drink', verbose_name='order')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drink_queue', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'order',
                'verbose_name_plural': 'orders',
            },
        ),
    ]
