# Generated by Django 3.2.7 on 2021-09-25 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='image',
            field=models.FileField(null=True, upload_to='D:\\Coding\\Bartender_Assistant/static/media', verbose_name='image'),
        ),
    ]
