# Generated by Django 3.2.7 on 2021-10-12 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientstorage',
            name='type',
            field=models.CharField(choices=[('LIQUID', 'liquid'), ('FRUIT', 'fruit'), ('VEGETABLE', 'vegetable'), ('SNACK', 'snack'), ('OTHER', 'other')], max_length=255, verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='user',
            name='expire_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='expire date'),
        ),
        migrations.AlterField(
            model_name='user',
            name='one_use_account_password',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='one-time account password'),
        ),
    ]
