# Generated by Django 3.2.7 on 2021-12-08 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Earnings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sum_date",
                    models.DateField(auto_now_add=True, verbose_name="sum date"),
                ),
                ("sum", models.PositiveIntegerField(verbose_name="sum")),
            ],
        ),
        migrations.RemoveField(
            model_name="user",
            name="is_customer",
        ),
        migrations.AddField(
            model_name="drink",
            name="amount",
            field=models.PositiveIntegerField(default=1, verbose_name="amount"),
        ),
        migrations.AddField(
            model_name="drink",
            name="image",
            field=models.FileField(
                null=True, upload_to="drinks", verbose_name="drink image"
            ),
        ),
        migrations.AddField(
            model_name="drink",
            name="preparation_description",
            field=models.CharField(
                default=None, max_length=1024, verbose_name="preparation description"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="drink",
            name="price",
            field=models.PositiveIntegerField(default=0, verbose_name="price"),
        ),
        migrations.AddField(
            model_name="drink",
            name="type",
            field=models.CharField(
                choices=[
                    ("ONE_SHOT", "one shot"),
                    ("MULTIPLE_SHOT", "multiple shot"),
                    ("ALCOHOLIC", "alcoholic"),
                    ("NON_ALCOHOLIC", "non alcoholic"),
                ],
                default=None,
                max_length=255,
                verbose_name="type",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="drinkqueue",
            name="order_date",
            field=models.DateField(
                auto_now_add=True, default=None, verbose_name="order date"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                blank=True,
                choices=[("bt", "bartender"), ("wt", "waiter"), ("ct", "customer")],
                max_length=2,
                null=True,
                verbose_name="role",
            ),
        ),
        migrations.AlterField(
            model_name="drink",
            name="date_creation",
            field=models.DateField(auto_now_add=True, verbose_name="date created"),
        ),
        migrations.AlterField(
            model_name="drink",
            name="date_modified",
            field=models.DateField(auto_now=True, verbose_name="date modified"),
        ),
        migrations.AlterField(
            model_name="ingredientstorage",
            name="image",
            field=models.FileField(
                null=True, upload_to="ingredients", verbose_name="image"
            ),
        ),
        migrations.AlterField(
            model_name="ingredientstorage",
            name="type",
            field=models.CharField(
                choices=[
                    ("LIQUID", "liquid"),
                    ("FRUIT", "fruit"),
                    ("VEGETABLE", "vegetable"),
                    ("SNACK", "snack"),
                    ("OTHER", "other"),
                ],
                max_length=255,
                verbose_name="type",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="expire_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="expire date"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="one_use_account_password",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                verbose_name="one-time account password",
            ),
        ),
    ]
