# Generated by Django 3.2.7 on 2021-10-14 07:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20211012_2238'),
    ]

    operations = [
        migrations.CreateModel(
            name='Earnings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sum_date', models.DateField(auto_now_add=True, verbose_name='sum date')),
                ('sum', models.PositiveIntegerField(verbose_name='sum')),
            ],
        ),
        migrations.AddField(
            model_name='drink',
            name='price',
            field=models.PositiveIntegerField(default=0, verbose_name='price'),
        ),
        migrations.AddField(
            model_name='drinkqueue',
            name='order_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='order date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='is_waiter',
            field=models.BooleanField(default=False, verbose_name='waiter'),
        ),
        migrations.AlterField(
            model_name='drink',
            name='date_creation',
            field=models.DateField(auto_now_add=True, verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='drink',
            name='date_modified',
            field=models.DateField(auto_now=True, verbose_name='date modified'),
        ),
    ]
