# Generated by Django 3.2.7 on 2021-10-14 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20211014_0940'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_customer',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_waiter',
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('bt', 'bartender'), ('wt', 'waiter'), ('ct', 'customer')], max_length=2, null=True, verbose_name='role'),
        ),
    ]
