# Generated by Django 3.2.7 on 2021-09-25 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_ingredientstorage_storage_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientstorage',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredient_storage', to='core.ingredient', unique=True, verbose_name='ingredient'),
        ),
    ]
