# Generated by Django 3.2.7 on 2022-01-03 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_ingredientstorage_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="drink",
            name="image",
            field=models.FileField(
                blank=True, null=True, upload_to="drinks", verbose_name="drink image"
            ),
        ),
    ]
