# Generated by Django 3.2.7 on 2021-11-11 13:26

import django.contrib.postgres.fields.citext
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20211014_0950'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredientstorage',
            name='image',
        ),
        migrations.AlterField(
            model_name='drink',
            name='name',
            field=django.contrib.postgres.fields.citext.CICharField(max_length=255, unique=True, verbose_name='name'),
        ),
    ]
