# Generated by Django 3.2.7 on 2021-09-25 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_ingredientstorage_ingredient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='unit',
            field=models.CharField(choices=[('LITER', 'l'), ('PIECE', 'pc')], max_length=255, verbose_name='unit'),
        ),
    ]
