# Generated by Django 3.2.7 on 2022-01-09 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_drink_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='customer_table',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='customer table'),
        ),
    ]
