# Generated by Django 3.2.7 on 2021-09-25 17:48

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_ingredient_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='unit',
            field=models.CharField(choices=[('LITER', 'liter'), ('PIECE', 'piece')], max_length=255, verbose_name='unit'),
        ),
        migrations.AlterField(
            model_name='ingredientneeded',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='amount needed'),
        ),
    ]
