# Generated by Django 3.2.7 on 2022-01-11 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_user_customer_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drinkqueue',
            name='status',
            field=models.CharField(choices=[('CREATED', 'created'), ('ACCEPTED', 'accepted'), ('IN_PROGRESS', 'in progress'), ('COMPLETED', 'completed'), ('REJECTED', 'rejected'), ('CANCELED', 'canceled')], max_length=255, verbose_name='complicated'),
        ),
    ]
