# Generated by Django 3.2.7 on 2021-11-13 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_drink_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='drink',
            name='amount',
            field=models.PositiveIntegerField(default=1, verbose_name='amount'),
        ),
        migrations.AddField(
            model_name='drink',
            name='preparation_description',
            field=models.CharField(default='', max_length=1024, verbose_name='preparation description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='drink',
            name='type',
            field=models.CharField(choices=[('ONE_SHOT', 'one shot'), ('MULTIPLE_SHOT', 'multiple shot'), ('ALCOHOLIC', 'alcoholic'), ('NON_ALCOHOLIC', 'non alcoholic')], default='', max_length=255, verbose_name='type'),
            preserve_default=False,
        ),
    ]
