# Generated by Django 3.2.7 on 2022-01-11 21:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_alter_drinkqueue_order_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="drinkqueue",
            name="storage_order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="drink_queue",
                to="core.ingredientstorage",
                verbose_name="order",
            ),
        ),
        migrations.AddField(
            model_name="ingredientstorage",
            name="can_be_ordered",
            field=models.BooleanField(default=False, verbose_name="can be ordered"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="ingredientstorage",
            name="has_alcohol",
            field=models.BooleanField(default=False, verbose_name="has alcohol"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="ingredientstorage",
            name="price",
            field=models.PositiveIntegerField(
                blank=True, default=0, verbose_name="price"
            ),
        ),
        migrations.AlterField(
            model_name="drinkqueue",
            name="drink",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="drink_queue",
                to="core.drink",
                verbose_name="order",
            ),
        ),
        migrations.AlterField(
            model_name="drinkqueue",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="drink_queue",
                to=settings.AUTH_USER_MODEL,
                verbose_name="user",
            ),
        ),
        migrations.AlterField(
            model_name="ingredientstorage",
            name="type",
            field=models.CharField(
                choices=[
                    ("LIQUID", "liquid"),
                    ("BEER", "beer"),
                    ("FRUIT", "fruit"),
                    ("VEGETABLE", "vegetable"),
                    ("SNACK", "snack"),
                    ("OTHER", "other"),
                ],
                max_length=255,
                verbose_name="type",
            ),
        ),
        migrations.AlterField(
            model_name="ingredientstorage",
            name="unit",
            field=models.CharField(
                choices=[
                    ("MILLILITER", "milliliter"),
                    ("PIECE", "piece"),
                    ("PACK", "pack"),
                ],
                max_length=255,
                verbose_name="unit",
            ),
        ),
    ]
