# Generated by Django 3.2.7 on 2021-09-25 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20210925_2007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredientneeded',
            name='ingredient',
        ),
        migrations.RemoveField(
            model_name='ingredientstorage',
            name='ingredient',
        ),
        migrations.AddField(
            model_name='ingredientstorage',
            name='image',
            field=models.FileField(null=True, upload_to='D:\\Coding\\Bartender_Assistant/static/media', verbose_name='image'),
        ),
        migrations.AddField(
            model_name='ingredientstorage',
            name='name',
            field=models.CharField(default='None', max_length=255, unique=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='ingredientstorage',
            name='type',
            field=models.CharField(choices=[('LIQUID', 'liquid'), ('OTHER', 'other')], default=None, max_length=255, verbose_name='type'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ingredientstorage',
            name='unit',
            field=models.CharField(choices=[('LITER', 'liter'), ('PIECE', 'piece')], default=None, max_length=255, verbose_name='unit'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Ingredient',
        ),
    ]
