# Generated by Django 3.2.7 on 2022-01-17 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20220111_2223'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DrinkQueue',
            new_name='Orders',
        ),
        migrations.AlterField(
            model_name='ingredientstorage',
            name='storage_amount',
            field=models.PositiveIntegerField(verbose_name='amount in storage'),
        ),
    ]
