# Generated by Django 3.2.7 on 2021-09-25 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20210925_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientstorage',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='name'),
        ),
    ]
