# Generated by Django 3.2.7 on 2021-09-25 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_ingredientstorage_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientstorage',
            name='unit',
            field=models.CharField(choices=[('MILLILITER', 'milliliter'), ('PIECE', 'piece')], max_length=255, verbose_name='unit'),
        ),
    ]
