# Generated by Django 3.2.7 on 2022-01-19 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20220117_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredientstorage',
            name='storage_amount_calculation_margin',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='calculation margin of amount in storage'),
        ),
    ]
