# Generated by Django 3.2.11 on 2022-02-01 00:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_ingredientstorage_storage_amount_calculation_margin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='drink',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order', to='core.drink', verbose_name='order'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('CREATED', 'created'), ('ACCEPTED', 'accepted'), ('IN_PROGRESS', 'in progress'), ('COMPLETED', 'completed'), ('REJECTED', 'rejected'), ('CANCELED', 'canceled')], max_length=255, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='storage_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order', to='core.ingredientstorage', verbose_name='order'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
